# A short, descriptive name of this building block collection
name: Grokking OGC Building Blocks

# Short abstract for this collection (optional)
abstract: |
  This is a repository to play with building blocks and get to grips with the inner workings and functionality.

# Description for this collection (optional)
description: |
  More information on OGC Building Blocks can be found on the [site](https://ogcincubator.github.io/bblocks-docs/).

  The instructions for the setup are to be found [here](https://ogcincubator.github.io/bblocks-docs/create).

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: tikouka.grok.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://ogcincubator.github.io/bblock-prov-schema/build/register.json
  - https://ogcincubator.github.io/geodcat-ogcapi-records/build/register.json

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available